name: nightly
on:
  # run this workflow every night at 3am
  schedule:
    - cron: '0 3 * * *'
  # or when the user triggers it from GitHub Actions page
  workflow_dispatch:
jobs:
  names:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3
      - name: Install ğŸ“¦
        uses: cypress-io/github-action@v5
        with:
          runTests: false
      - name: Print E2E tests ğŸ–¨ï¸
        run: npm run names
      - name: Print Component tests ğŸ–¨ï¸
        run: npm run names:component

  nightly:
    runs-on: ubuntu-22.04

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit
      # and push the changed files back to the repository.
      contents: write

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3
      - name: Print Node version
        run: node -v

      # https://github.com/cypress-io/github-action
      - name: Cypress component tests
        # skip this step for now
        if: ${{ false }}
        uses: cypress-io/github-action@v5
        with:
          # catch any it.only left in the code
          build: npm run only
          component: true

      - name: Cypress E2E tests
        uses: cypress-io/github-action@v5
        with:
          # previous step has already installed everything
          install: false
          start: npm start
          wait-on: 'http://127.0.0.1:3000'

      - name: Code coverage summary ğŸ“Š
        run: npx nyc report

      - name: Store code coverage folder ğŸ“ˆ
        # https://github.com/actions/upload-artifact
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage
          path: coverage/

      - name: Update code coverage badge ğŸªª
        # only update the README from the main branc
        if: github.ref == 'refs/heads/main'
        run: npm run cc-badge

      # https://github.com/bahmutov/find-cypress-specs
      - name: Update the number of tests badge ğŸªª
        # only update the README from the main branc
        if: github.ref == 'refs/heads/main'
        run: npm run badge:tests

      - name: Commit any changed files ğŸ’¾
        # only update the README from the main branc
        if: github.ref == 'refs/heads/main'
        # https://github.com/stefanzweifel/git-auto-commit-action
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Updated badges
          branch: main
          file_pattern: README.md
